### ISSUE TITLE
Create better workflow with web storage

### ISSUE THREAD

**Issue by Plongy** [datasektionen/motioner#8]
Suger lite när man skrivet en fin propp, genererar en pdf och märker i efterhand att man klantat sig och råkat stava fel på något.

Vore soft om det fanns lite JS som lagrade din input i web storage och hämtar den när du kommer till sidan.

**Comment by jonasdahl** [comment]
Fixed as of 4144467705051c9b8287c5bf087b0bd802be753f

**Comment by Plongy** [comment]
Ooooohhhhh <3
